#!/bin/bash
#Figil writed by alireza.amirsamimi@ubuntu.ir
case_function_per (){
  case "$line" in
    "ض")
    xdotool getactivewindow windowfocus --sync type "q";;
    "ص")
    xdotool getactivewindow windowfocus --sync type "w";;
    "ث")
    xdotool getactivewindow windowfocus --sync type "e";;
    "ق")
    xdotool getactivewindow windowfocus --sync type "r";;
    "ف")
    xdotool getactivewindow windowfocus --sync type "t";;
    "غ")
    xdotool getactivewindow windowfocus --sync type "y";;
    "ع")
    xdotool getactivewindow windowfocus --sync type "u";;
    "ه")
    xdotool getactivewindow windowfocus --sync type "i";;
    "خ")
    xdotool getactivewindow windowfocus --sync type "o";;
    "ح")
    xdotool getactivewindow windowfocus --sync type "p";;
    "ج")
    xdotool getactivewindow windowfocus --sync type "[";;
    "چ")
    xdotool getactivewindow windowfocus --sync type "]";;
    "ش")
    xdotool getactivewindow windowfocus --sync type "a";;
    "س")
    xdotool getactivewindow windowfocus --sync type "s";;
    "ی")
    xdotool getactivewindow windowfocus --sync type "d";;
    "ب")
    xdotool getactivewindow windowfocus --sync type "f";;
    "ل")
    xdotool getactivewindow windowfocus --sync type "g";;
    "ا")
    xdotool getactivewindow windowfocus --sync type "h";;
    "ت")
    xdotool getactivewindow windowfocus --sync type "j";;
    "ن")
    xdotool getactivewindow windowfocus --sync type "k";;
    "م")
    xdotool getactivewindow windowfocus --sync type "l";;
    "ک")
    xdotool getactivewindow windowfocus --sync type ";";;
    "گ")
    xdotool getactivewindow windowfocus --sync type "'";;
    "ظ")
    xdotool getactivewindow windowfocus --sync type "z";;
    "ط")
    xdotool getactivewindow windowfocus --sync type "x";;
    "ز")
    xdotool getactivewindow windowfocus --sync type "c";;
    "ر")
    xdotool getactivewindow windowfocus --sync type "v";;
    "ذ")
    xdotool getactivewindow windowfocus --sync type "b";;
    "د")
    xdotool getactivewindow windowfocus --sync type "n";;
    "پ")
    xdotool getactivewindow windowfocus --sync type "m";;
    "و")
    xdotool getactivewindow windowfocus --sync type ",";;
    "ژ‍")
    xdotool getactivewindow windowfocus --sync type "C";;
    "۱")
    xdotool getactivewindow windowfocus --sync type "1";;
    "۲")
    xdotool getactivewindow windowfocus --sync type "2";;
    "۳")
    xdotool getactivewindow windowfocus --sync type "3";;
    "۴")
    xdotool getactivewindow windowfocus --sync type "4";;
    "۵")
    xdotool getactivewindow windowfocus --sync type "5";;
    "۶")
    xdotool getactivewindow windowfocus --sync type "6";;
    "۷")
    xdotool getactivewindow windowfocus --sync type "7";;
    "۸")
    xdotool getactivewindow windowfocus --sync type "8";;
    "۹")
    xdotool getactivewindow windowfocus --sync type "9";;
    "۰")
    xdotool getactivewindow windowfocus --sync type "0";;
    "")
    xdotool getactivewindow windowfocus --sync type " ";;
    ")")
    xdotool getactivewindow windowfocus --sync type "(";;
    "(")
    xdotool getactivewindow windowfocus --sync type ")";;
    "؟")
    xdotool getactivewindow windowfocus --sync type "?";;
    "٬")
    xdotool getactivewindow windowfocus --sync type "@";;
    "٪")
    xdotool getactivewindow windowfocus --sync type "%";;
    "×")
    xdotool getactivewindow windowfocus --sync type "^";;
    "،")
    xdotool getactivewindow windowfocus --sync type "&";;
    *)
    xdotool getactivewindow windowfocus --sync type "$line";;
  esac
}
case_function_en (){
  case $line in
    "q"|"Q")
    xdotool getactivewindow windowfocus --sync type "ض";;
    "w"|"W")
    xdotool getactivewindow windowfocus --sync type "ص";;
    "e"|"E")
    xdotool getactivewindow windowfocus --sync type "ث";;
    "r"|"R")
    xdotool getactivewindow windowfocus --sync type "ق";;
    "t"|"T")
    xdotool getactivewindow windowfocus --sync type "ف";;
    "y"|"Y")
    xdotool getactivewindow windowfocus --sync type "غ";;
    "u"|"U")
    xdotool getactivewindow windowfocus --sync type "ع";;
    "i"|"I")
    xdotool getactivewindow windowfocus --sync type "ه";;
    "o"|"O")
    xdotool getactivewindow windowfocus --sync type "خ";;
    "p"|"P")
    xdotool getactivewindow windowfocus --sync type "ح";;
    "[")
    xdotool getactivewindow windowfocus --sync type "ج";;
    "]")
    xdotool getactivewindow windowfocus --sync type "چ";;
    "a"|"A")
    xdotool getactivewindow windowfocus --sync type "ش";;
    "s"|"S")
    xdotool getactivewindow windowfocus --sync type "س";;
    "d"|"D")
    xdotool getactivewindow windowfocus --sync type "ی";;
    "f"|"F")
    xdotool getactivewindow windowfocus --sync type "ب";;
    "g"|"G")
    xdotool getactivewindow windowfocus --sync type "ل";;
    "h"|"H")
    xdotool getactivewindow windowfocus --sync type "ا";;
    "j"|"J")
    xdotool getactivewindow windowfocus --sync type "ت";;
    "k"|"K")
    xdotool getactivewindow windowfocus --sync type "ن";;
    "l"|"L")
    xdotool getactivewindow windowfocus --sync type "م";;
    ";")
    xdotool getactivewindow windowfocus --sync type "ک";;
    "'")
    xdotool getactivewindow windowfocus --sync type "گ";;
    "z"|"Z")
    xdotool getactivewindow windowfocus --sync type "ظ";;
    "x"|"X")
    xdotool getactivewindow windowfocus --sync type "ط";;
    "c")
    xdotool getactivewindow windowfocus --sync type "ز";;
    "v"|"V")
    xdotool getactivewindow windowfocus --sync type "ر";;
    "b"|"B")
    xdotool getactivewindow windowfocus --sync type "ذ";;
    "n"|"N")
    xdotool getactivewindow windowfocus --sync type "د";;
    "m"|"M")
    xdotool getactivewindow windowfocus --sync type "پ";;
    ",")
    xdotool getactivewindow windowfocus --sync type "و";;
    "C")
    xdotool getactivewindow windowfocus --sync type "ژ";;
    "1")
    xdotool getactivewindow windowfocus --sync type "۱";;
    "2")
    xdotool getactivewindow windowfocus --sync type "۲";;
    "3")
    xdotool getactivewindow windowfocus --sync type "۳";;
    "4")
    xdotool getactivewindow windowfocus --sync type "۴";;
    "5")
    xdotool getactivewindow windowfocus --sync type "۵";;
    "6")
    xdotool getactivewindow windowfocus --sync type "۶";;
    "7")
    xdotool getactivewindow windowfocus --sync type "۷";;
    "8")
    xdotool getactivewindow windowfocus --sync type "۸";;
    "9")
    xdotool getactivewindow windowfocus --sync type "۹";;
    "0")
    xdotool getactivewindow windowfocus --sync type "۰";;
    "?")
    xdotool getactivewindow windowfocus --sync type "؟";;
    "(")
    xdotool getactivewindow windowfocus --sync type ")";;
    ")")
    xdotool getactivewindow windowfocus --sync type "(";;
    "")
    xdotool getactivewindow windowfocus --sync type " ";;
    "@")
    xdotool getactivewindow windowfocus --sync type "٬";;
    "#")
    xdotool getactivewindow windowfocus --sync type "٫";;
    "%")
    xdotool getactivewindow windowfocus --sync type "٪";;
    "^")
    xdotool getactivewindow windowfocus --sync type "×";;
    "&")
    xdotool getactivewindow windowfocus --sync type "،";;
    *)
    xdotool getactivewindow windowfocus --sync type "$line";;
  esac
}
sleep 1
#copy clipboard
clipboard=$(xclip -o -sel clip )
#Spliting clipbord to letters and saving them in a text file in seperate lines
echo $clipboard | grep -o . > /tmp/fingil.txt
#checking encoding of file.utf8 is for persian.
encode_type=$(file -bi /tmp/fingil.txt)
#reading text file lines and converting them
while read -r line;do
  if [ "$encode_type" == "text/plain; charset=utf-8" ];then
    case_function_per
  else
    case_function_en
  fi
done < /tmp/fingil.txt
rm -r /tmp/fingil.txt
exit
