#!/bin/bash
#Figil written by alireza.amirsamimi@ubuntu.ir based on two scripts that written by fzero@rubi.gd 

case_function_per () {
    persian=( ض ص ث ق ف غ ع ه خ ح ج چ ش س ی ب ل ا ت ن م ک گ ظ ط ز ر ذ د پ و ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹ ۰ ! ٬ ٫ ﷼ ٪ × ، ؛ )
    english=( q w e r t y u i o p \[ \] a s d f g h j k l \; \' z x c v b n m , 1 2 3 4 5 6 7 8 9 0 ! @ \# \$ % \^ \& \' )
    len=$(echo ${#english[*]})
    arg=$@
    for ((i=1 ; i < $len ; i++)) do
        arg=${arg//${persian[$i]}/${english[$i]}}
    done

    echo "$arg"
}

case_function_en () {
    persian=( ض ص ث ق ف غ ع ه خ ح ج چ ش س ی ب ل ا ت ن م ک گ ظ ط ز ر ذ د پ و ۱ ۲ ۳ ۴ ۵ ۶ ۷ ۸ ۹ ۰ ! ٬ ٫ ﷼ ٪ × ، ؛ )
    english=( q w e r t y u i o p \[ \] a s d f g h j k l \; \' z x c v b n m , 1 2 3 4 5 6 7 8 9 0 ! @ \# \$ % \^ \& \' )
    len=$(echo ${#persian[*]})
    arg=$@
    for ((i=1 ; i < $len ; i++)) do
        arg=${arg//${english[$i]}/${persian[$i]}}
    done

    echo "$arg"
}
window_pid=$(xdotool getactivewindow)
#copy clipboard
clipboard=$(xclip -o -sel clip )
while [ -f /tmp/fingil.txt ];do
    sleep 0.5
done    
#Spliting clipbord to letters and saving them in a text file in seperate lines
echo $clipboard > /tmp/fingil.txt
#checking encoding of file.utf8 is for persian.
encode_type=$(file -bi /tmp/fingil.txt)
#reading text file lines and converting them

if [ "$encode_type" == "text/plain; charset=utf-8" ];then
    case_function_per $clipboard
    sleep 1
    xdotool type --delay 400 --window $window_pid "$(case_function_per $clipboard)"
else
    case_function_en  $clipboard
    sleep 1
    xdotool  type --delay 400 --window $window_pid "$(case_function_en $clipboard)"
fi
rm /tmp/fingil.txt
exit
